# ============================================================================
# Docker Compose - Surcharge DEV (Registry)
# ============================================================================
#
# USAGE:
#   ENV=dev docker-compose -f docker-compose.registry.yml -f docker-compose.dev-registry.yml up -d
#
# ============================================================================

services:
    __PROJECT_NAME__-api-__ENV__:
        ports:
            - "${DEV_PORT:-8001}:80"

        environment:
            - ENVIRONMENT=dev
            - LOG_LEVEL=DEBUG
            - RELOAD=true

        labels:
            - "traefik.enable=false"

    __PROJECT_NAME__-redis-__ENV__:
        ports:
            - "${REDIS_DEV_PORT:-6379}:6379"

